### ISSUE TITLE
Not working on Ubuntu 12.04 vanilla. Parent directory /etc/postgresql/9.1/main does not exist.

### ISSUE THREAD

**Issue by sergiotapia** [hw-cookbooks/postgresql#108]
I'm trying to use this recipe to install PostgreSQL on a DigitalOcean VPS.

When running `knife solo cook root@[ip-address]" I get:

* service[postgresql] action start (up to date)
Recipe: postgresql::server
  * template[/etc/postgresql/9.1/main/postgresql.conf] action create
    * Parent directory /etc/postgresql/9.1/main does not exist.
================================================================================
Error executing action `create` on resource 'template[/etc/postgresql/9.1/main/postgresql.conf]'
================================================================================

Chef::Exceptions::EnclosingDirectoryDoesNotExist
------------------------------------------------
Parent directory /etc/postgresql/9.1/main does not exist.

Resource Declaration:
---------------------
# In /root/chef-solo/cookbooks-2/postgresql/recipes/server.rb

 62: template "#{node['postgresql']['dir']}/postgresql.conf" do
 63:   source "postgresql.conf.erb"
 64:   owner "postgres"
 65:   group "postgres"
 66:   mode 0600
 67:   notifies change_notify, 'service[postgresql]', :immediately
 68: end
 69: 

Compiled Resource:
------------------
# Declared in /root/chef-solo/cookbooks-2/postgresql/recipes/server.rb:62:in `from_file'

template("/etc/postgresql/9.1/main/postgresql.conf") do
  provider Chef::Provider::Template
  action "create"
  retries 0
  retry_delay 2
  path "/etc/postgresql/9.1/main/postgresql.conf"
  backup 5
  atomic_update true
  source "postgresql.conf.erb"
  cookbook_name :postgresql
  recipe_name "server"
  mode 384
  owner "postgres"
  group "postgres"
end

[2014-01-27T23:56:57-05:00] ERROR: Running exception handlers
[2014-01-27T23:56:57-05:00] ERROR: Exception handlers complete
[2014-01-27T23:56:57-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 12 resources updated
[2014-01-27T23:56:57-05:00] ERROR: template[/etc/postgresql/9.1/main/postgresql.conf] (postgresql::server line 62) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/postgresql/9.1/main does not exist.
[2014-01-27T23:56:57-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.

**Comment by slyness** [comment]
In combination with #175 . #222 will correct this.
