### ISSUE TITLE
FATAL:  could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied

### ISSUE THREAD

**Issue by volkanunsal** [hw-cookbooks/postgresql#156]
Hi there,

As I use this recipe to install postgresql, I run into this error:

    FATAL:  could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied

I have tried all the recommended solutions to solve it, including changing the owner and group of the key to postgres. Nothing works. To verify that it doesn't work even with that, I ran the following command on the key:

    sudo -u postgres cat  ssl-cert-snakeoil.key

The result was:

   cat: ssl-cert-snakeoil.key: Permission denied 

(I am running Ubuntu 14.04 with Vagrant. Using passenger/ruby-20 image and Docker as provider.)

**Comment by tobixen** [comment]
Found this issue through a web search.  Probably not related to hw-cookbooks, but ... I had the same issue after a package update and postgres restart, no AUFS involved, could also verify that postgres had read permissions both on the directory and the file.  Giving postgres _write_ permission on the keyfile and certfile solved the problem.  This doesn't make sense at all ...

**Comment by gvb** [comment]
Same experience as @tobixen, running Ubuntu 12.04, did an upgrade of postgresql, and was locked out until I changed ownership to postgres (giving write permission) to *both* /etc/ssl/private/ssl-cert-snakeoil.key and /etc/ssl/certs/ssl-cert-snakeoil.pem

**Comment by lkarsten** [comment]
Just ran into something similar on an ubuntu 12.04 instance.

Seems like postgresql reduces privileges down to the postgres user, but forget to bring the group memberships with it.

g+w isn't necessary, don't do that. i ended up just chowning the snakeoil key and cert to user postgres.

**Comment by iwan** [comment]
Same problem here (postgresql service suddenly stopped and was unable to start) solved with the same solution on Ubuntu 12.10:

    sudo chown postgres /etc/ssl/private/ssl-cert-snakeoil.key
    sudo chown postgres /etc/ssl/certs/ssl-cert-snakeoil.pem

**Comment by tarak** [comment]
Have you tried to add the postgres user to the ssl-cert group which is created while installing the ca-certificate package? As far as I can remember the group exists just for this purpose. The keys in `/etc/ssl/private` should be readable for the members of that group. I think the `www-data` user for apache2 is actually member of that group too. I could be wrong though...

**Comment by tarak** [comment]
ok, reading your comments I have to admit that I misread a few details. Sorry for that... I'll try to verify this on an Ubuntu 14.04 system tomorrow at work and report back.

**Comment by gvb** [comment]
@tarak On my systems the postgres user is in the ssl-cert group and, as user "postgres", I can cat both files so it definitely has read access. Evidence indicates postgres is opening the file "rw" rather than "r". Doing chown postgres work-around works because it is u=rw (although I have not verified this by setting u=r).

IIRC, setting g=rw is not allowed, postgres (probably the start up script) refuses to run with that configuration (security).

**Comment by inactivist** [comment]
I think [this bug](https://wiki.postgresql.org/wiki/May_2015_Fsync_Permissions_Bug) and the suggested fix is relevant.

**Comment by wibinem** [comment]
now i can startup the postgresql after read in <a href="https://wiki.postgresql.org/wiki/May_2015_Fsync_Permissions_Bug#May_2015_fsync_Permissions_Bug_FAQ">here</a> but when i try to login, it won't. i try the command psql, the output

psql: FATAL:  the database system is starting up

anyone can help me?

thank you

**Comment by iashwash** [comment]
The fix for the underlying issue has been released http://www.postgresql.org/about/news/1590/

**Comment by atulya** [comment]
Try this 
sudo chown postgres:postgres /etc/ssl/private/ssl-cert-snakeoil.key

**Comment by GabLeRoux** [comment]
hmm, in my case, solution was to add `postgres` to `ssl-cert` group. Not quite sure this was the right thing to do, but it did work.

    gpasswd -a postgres ssl-cert

**Comment by kevinmoilar** [comment]
was the missing ssl-cert group for the postgres user here on debian (usermod postgres -g ssl-cert)

**Comment by ffleandro** [comment]
The correct permissions for both the snakeoil key and cert are 0600 if file owned by ssl-cert or 0640 if owned by root
