### ISSUE TITLE
Cannot install shared_preload_libraries

### ISSUE THREAD

**Issue by avinogradov** [hw-cookbooks/postgresql#192]
In case then you are trying to install pg_stat_statements extension you will encounter 'could not access file "pg_stat_statements": No such file or directory' error during PostgreSQL server restart.
The thing is that then you defined default['postgresql']['config']['shared_preload_libraries'] = 'pg_stat_statements' as mentioned in notes chef will try to restart PostgreSQL server right before installing this extension itself which will lead to error.

**Comment by GUI** [comment]
We ran into this as well, and I've submitted a pull request that should hopefully address the issue: https://github.com/hw-cookbooks/postgresql/pull/241
