### ISSUE TITLE
Chef-Solo:  Password Not Being Set

### ISSUE THREAD

**Issue by conradwt** [hw-cookbooks/postgresql#213]
I'm using chef-solo to provision a server.  Thus, I followed the Chef Solo Note instructions for setting up JSON attributes.  However, the password isn't being set because I cannot login with any password.  Are there additional steps that I need to follow here?

**Comment by lemattma** [comment]
Hey @conradwt , did you manage to make this work? I'm struggling with the same issue.

**Comment by conradwt** [comment]
@lemattma I ended up setting the permissions manually after doing the deploy to move forward regarding this issue.  Please see the link for the details:  

```
https://github.com/intercity/chef-repo/issues/144
```

**Comment by andre1810** [comment]
You´ve to set the password as JSON ATTRIBUTE in md5 format, set listening to all or specific ip adrresses and configure pg_hba options to permit connections from your client to the pg server:

```
"postgresql": {
    "password": {
      "postgres": "<your md5 password>"
    },
    "config": {
      "listen_addresses": "*"
    },
    "pg_hba": [
        {
          "type": "local", 
          "db": "all", 
          "user": "postgres", 
          "addr": "", 
          "method": "ident"
        },
        {
          "type": "host", 
          "db": "all", 
          "user": "all", 
          "addr": "127.0.0.1/32", 
          "method": "trust"
        },

        {
          "type": "host", 
          "db": "all", 
          "user": "all", 
          "addr": "192.168.56.0/24", 
          "method": "trust"
        }]
      }
  ,
  "run_list": ["recipe[postgresql::server]"],
```

The password needs to be in md5 format. Refer to the [Chef Solo Note](https://github.com/hw-cookbooks/postgresql#chef-solo-note) how to create it.

**Comment by conradwt** [comment]
@andre1810 I would recommend adding these additional details to the Chef Solo Note because just setting the password to "<your md5 password>" simply doesn't work.  In any case, I'll give this a try and report back.

**Comment by conradwt** [comment]
@andre1810 After adding the "config" and "pg_hba" sub JSON documents to my nodes file, things are working without any manual configuration.  Thanks again for the information.
