### ISSUE TITLE
postgresql-client-9.3 not Found on Ubuntu 14.10

### ISSUE THREAD

**Issue by ylleochan** [hw-cookbooks/postgresql#214]
Like #140, running the cookbook with default settings on Ubuntu 14.10 fails because postgresql-client-9.3 is not there as an install candidate. The version for 14.10 looks to be postgresql-client-9.4.

**Comment by noahgibbs** [comment]
This looks strongly related to https://github.com/hw-cookbooks/postgresql/issues/217

**Comment by SimonKaluza** [comment]
I ran into this as well and had to use the workaround with many attributes posted in https://github.com/hw-cookbooks/postgresql/issues/217 as well

**Comment by slyness** [comment]
Corrections coming in #314

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0
