### ISSUE TITLE
Wrong service provider used on Linux Mint

### ISSUE THREAD

**Issue by rlipscombe** [hw-cookbooks/postgresql#216]
When using the 'postgresql' (https://supermarket.chef.io/cookbooks/postgresql) cookbook, chef-solo (v11.16.4) fails with:

    Error executing action `enable` on resource 'service[postgresql]'
    File '/etc/init/postgresql.conf' does not exist

This is because chef assumes that Linux Mint uses upstart; for the postgresql-9.3 package, it's still using init.d.

So the `action [:enable]` attribute does the wrong thing.

(Originally reported as https://github.com/opscode/chef/issues/2726)

**Comment by slyness** [comment]
Mint is not a supported distribution.
