### ISSUE TITLE
uninitialized constant Opscode::OpenSSL

### ISSUE THREAD

**Issue by kramvan1** [hw-cookbooks/postgresql#225]
Looks like the latest version of openssl cookbook just changed this namespace to OpenSSLCookbook

So, need matching patch here and update metadata to point to >= 3.0.0 of that cookbook

See https://github.com/opscode-cookbooks/openssl/commit/03e0e9b690fd9db3d81779762c810371f0fe7e1e

**Comment by kramvan1** [comment]
I think this will do the trick: https://github.com/hw-cookbooks/postgresql/pull/226

**Comment by gsaslis** [comment]
yes, also had this, and i reverted back to 2.0.2 of the openssl cookbook for now. The fix would help! ;)

**Comment by slyness** [comment]
Release 3.4.18 will correctly `depends "openssl", "~> 4.0.0" ` which will resolve this issue. They reverted the changes from last week and release the 4.0.0 release.

**Comment by gsaslis** [comment]
nice!! 

Am a little confused by your versioning though... : )  Shouldn't these types of changes make it to a minor version upgrade? Is this considered a patch / bugfix?

I'm just saying cause I use ' >~ ' in my cookbook dependencies, to accept patches and bugfixes to other cookbooks, but not risk breaking my cook when someone releases a non-backwards compatible change... ; )
