### ISSUE TITLE
Peer authentication failed for user "postgres" on initial chef run (reboot + 2nd run works fine)

### ISSUE THREAD

**Issue by nlochschmidt** [hw-cookbooks/postgresql#232]
I am trying to setup a fairly simple Vagrantfile that boots a VM with postgresql and creates a couple of users and databases using [hw-cookbooks/database](https://github.com/hw-cookbooks/database). In the end I need access to the database from the host machine, so I change the `pg_hba.conf` by setting a couple of attributes in the Vagrantfile:

```js
chef.json = {
  "postgresql" => {
    "version" => "9.3",
    "password" => {
      "postgres" => "postgres",
    },
    "config" => {
      "listen_addresses" => "*"
    },
    "pg_hba" => [
      { "type" => 'host', "db" => 'all', "user" => 'all', "addr" => '10.0.0.0/16', "method" => 'md5' },
      { "type" => 'local', "db" => 'all', "user" => 'all', "addr" => '', "method" => 'trust' }
    ]
  }
}
```

Now, when I boot the VM for the first time I get `FATAL:  Peer authentication failed for user "postgres"`. When I reboot the VM and run chef again everything works as it should, but I destroy and reprovision the VM a couple of times per month and it's just cumbersome.

I also see this in my log:
```
INFO: template[/etc/postgresql/9.3/main/pg_hba.conf] not queuing delayed action restart on service[postgresql] (delayed), as it's already been queued
```
So my guess is this has to do with the service notification having been [changed from `:immediately` to `:delayed`]( https://github.com/hw-cookbooks/postgresql/commit/3447448b3a08a3f25d0420625b8627ea3d05c01d
) and therefore when I try to create the users and databases during the initial convergence run the default `pg_hba.conf` is still in effect.
 
Am I doing something wrong? Help would be appreciated.

**Comment by chr4** [comment]
I'm having a similar issue - Creating databases in the same Chef run as configuring postgresql seems to me like a regular usecase.
Was there a particular reason the action was changed to `:delayed`?

+1

**Comment by nlochschmidt** [comment]
I experienced this on 3.4.14 but can not reproduce this on 3.4.20. So it seems to be fixed.
