### ISSUE TITLE
issue 234 is locked

### ISSUE THREAD

**Issue by kplimack** [hw-cookbooks/postgresql#235]
Not letting me comment on my own ticket is not constructive.   It's a real problem that needs addressing,  you didnt even read the ticket.  Please try taking this seriously

**Comment by kplimack** [comment]
My ticket addresses #217, #224, #147.  Is that not constructive.

P.s.  terrible terrible terrible, did your face explode?

**Comment by kplimack** [comment]
No, then be a professional and unlock the comment and end your childish behavior

**Comment by nozpheratu** [comment]
@kplimack You couldn't have posted your ticket without being condescending about it? It's the opposite of constructive.
People would be more willing to take your issues seriously if you be cool about it.

**Comment by kplimack** [comment]
Hours working backwards to get this working may have taken some of my
patience away, so if I offended sorry, but my BOFH comment doesn't make my
point any less meaningful.
