### ISSUE TITLE
Downloads PGDG RPM package every time

### ISSUE THREAD

**Issue by Odaeus** [hw-cookbooks/postgresql#236]
I noticed this line taking a long time on every run:
```
Recipe: postgresql::yum_pgdg_postgresql
  * remote_file[/var/chef/cache/pgdg-centos93-9.3-1.noarch.rpm] action create
```

It originates from:
https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/yum_pgdg_postgresql.rb#L34
```ruby
# Download the PGDG repository RPM as a local file
remote_file "#{Chef::Config[:file_cache_path]}/#{repo_rpm_filename}" do
  source repo_rpm_url
  mode "0644"
end
```

There's no `not_if` guard to check if the package is already installed so isn't this downloading the file on every run?

**Comment by slyness** [comment]
This issue is no longer a problem. Closing.
