### ISSUE TITLE
Specifying Postgresql 9.4 on Ubuntu 12.04 LTS node creates wrong config file

### ISSUE THREAD

**Issue by johannesluedke** [hw-cookbooks/postgresql#254]
Adjusting (overrding) the attribute `:postgresql => {:version => '9.4'}` in the role for a node or on a node still creates an

    unix_socket_directory

entry in the postgresql.conf file, which is invalid option in this postgres version (renamed to unix_socket_directories). 
The if-statement in the line introducing this config

     default['postgresql']['config']['unix_socket_directory'] = '/var/run/postgresql' if node['postgresql']['version'].to_f < 9.3

(from postgresql/attributes/default.rb)
somehow doesn't get active. 
Hack Workaorund: If one overrides the version by setting `default['postgresql']['version'] = "9.4"` inside the `case node['platform']` block after the plaform version, it works.

Without this hack the postgresql chef cookbook is somehow stuck to use the standard 9.1 that was choosen for ubuntu 12.04.

**Comment by johannesluedke** [comment]
Looked around a bit more - is this something that would be fixed with #201 ?

**Comment by slyness** [comment]
This will be addressed soon. #314 
https://github.com/hw-cookbooks/postgresql/blob/dev_4.0.0/recipes/server_conf.rb#L27-L31

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0
