### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by gsaslis** [hw-cookbooks/postgresql#263]
The README.md states that log rotation is supported through the config_initdb recipe, using the following attributes: 
```
"log_rotation_age": "1d",
"log_rotation_size": "10MB"
```

However, I am not sure where these are actually used, since (if I understand correctly what I am seeing) I can see the attributes being set [here](https://github.com/hw-cookbooks/postgresql/blob/554143c814f0a0dfb178e424ac6017d610605325/attributes/default.rb#L195-L196) and [here](https://github.com/hw-cookbooks/postgresql/blob/b76660bb225b6b09c8bd54273abe5092164114a6/recipes/config_initdb.rb#L146-L147) but I can't really see them being read/used somewhere, e.g. so they would be applied in a configuration file... ?? 

Have I got something completely wrong? Am I missing something obvious?

**Comment by slyness** [comment]
`node['postgresql']['config']` is the hash that is used when the `postgresql.conf` template is written to the system. Here: https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/server_conf.rb#L42-L48

Which means that each item in the attribute hash when the recipe is evaluated it's `key` and `value` are written as lines in the resulting configuration file. Here: https://github.com/hw-cookbooks/postgresql/blob/develop/templates/default/postgresql.conf.erb#L6

You can modify these values by setting the two attributes:
`default['postgresql']['config']['log_rotation_age']` and `default['postgresql']['config']['log_rotation_size']`

**Comment by gsaslis** [comment]
spot on @slyness !! 

Thanks for that! :+1:
