### ISSUE TITLE
Server restarts every time Chef Client is run

### ISSUE THREAD

**Issue by ambientsound** [hw-cookbooks/postgresql#266]
Starting from release 3.4.19, the PostgreSQL server restarts every time Chef Client is run, even though the configuration has not changed.

**Comment by chr4** [comment]
This is so evil. happens even if restart policy is set to `:reload`.

**Comment by chr4** [comment]
This should be the evil commit: https://github.com/hw-cookbooks/postgresql/commit/5d056092ed7dae32229b6086c31a1071d3ec8d4b

**Comment by chr4** [comment]
Again, this is critical, as it causes downtime. **DO NOT USE** `v3.4.19` in production scenarios!

**Comment by cwjohnston** [comment]
Sorry for the trouble! I've reverted the commit in question and released v3.4.20 (see #267).
