### ISSUE TITLE
Use rubocop

### ISSUE THREAD

**Issue by rmoriz** [hw-cookbooks/postgresql#276]
There are many places with non-idiomatic code parts that in some cases seem to look broken, too.
Please add rubocop to the project.

I'll contribute and fix everything for you, if you (the maintainers) will work on the current open PRs.

**Comment by bottkv488** [comment]
+1

**Comment by tas50** [comment]
I've converted things to cookstyle and resolved the majority of the warnings. There's just a few that need to be hand tackled now. #365
