### ISSUE TITLE
Upgrade openssl dependency to current version, 4.2.x

### ISSUE THREAD

**Issue by mikelax** [hw-cookbooks/postgresql#278]
Right now this package is pinned to depend on openssl version 4.0.0
The current version of openssl is 4.2.0

Is there any reason to not upgrade to support the current version of openssl?

**Comment by tarak** [comment]
+1

**Comment by bottkv488** [comment]
+1

**Comment by ianbamforth** [comment]
+1

**Comment by rackspace-latina-media** [comment]
+1

Oddly enough, this caused issues because we were on version `postgresql 3.4.16` which had no specific version dependency, putting us at `openssl 4.2.0`, but after today we upgraded to `postgresql 3.4.20` and this rolled back the version using berks to `openssl 4.0.0`. No bueno ;)

**Comment by dude051** [comment]
+1

Oddly enough, this caused issues because we were on version postgresql 3.4.16 which had no specific version dependency, putting us at openssl 4.2.0, but after today we upgraded to postgresql 3.4.20 and this rolled back the version using berks to openssl 4.0.0. No bueno ;)

**Comment by thomas88** [comment]
The version constraint was only recently introduced and you can use v3.4.16 if you don't depend on any newer additions.

**Comment by eheydrick** [comment]
Would be great to see this fixed.
