### ISSUE TITLE
Using yum PGDG repo - wrong data dir and setup path

### ISSUE THREAD

**Issue by JCapriotti** [hw-cookbooks/postgresql#280]
Using custom RPM path for Postgres 9.4 and Fedora 21... specifically http://yum.postgresql.org/9.4/fedora/fedora-21-x86_64/pgdg-fedora94-9.4-2.noarch.rpm

The path to postgresql-setup and the data directory are incorrect. For example, data dir is /var/lib/pgsql/9.4/data and postgresql-setup is /usr/pgsql-9.4/bin/postgresql94-setup

Seems to happen consistently...

**Comment by slyness** [comment]
I'm working on an update that will address this. Should have something for testing soon.

**Comment by JCapriotti** [comment]
That's awesome, thanks for the update. I'd like to have poked at this myself but being new to Chef this cookbook isn't something I wanted to work on right away :)

**Comment by slyness** [comment]
Progress. Hopefully we'll be releasing changes soon that will address this. #314

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0
