### ISSUE TITLE
Error Install Postgres 9.2.13 on RHEL 7.1 EC2 Instance

### ISSUE THREAD

**Issue by vinsleo** [hw-cookbooks/postgresql#301]
I am using ami-25158352 to instantiate a EC2 box to install posters on it.
AT line number 82 of the server_redhat.rb recipe I get error saying 

execute[postgresql92-setup initdb postgresql] action run[2015-11-09T11:07:08-05:00] INFO: Processing execute[postgresql92-setup initdb postgresql] action run (postgresql::server_redhat line 82)

================================================================================
                                 Error executing action `run` on resource 'execute[postgresql92-setup initdb postgresql]'
                                 ================================================================================

                                 Errno::ENOENT
                                 -------------
                                 No such file or directory - postgresql92-setup

I looked onto the box and realised its called 
postgresql-setup and not postgresql92-setup

script is checking for version of RHEL > 7
but probably in version 7.1 this has been restored to use the executable without the appended version number of postgres server

**Comment by chewi** [comment]
I've just been hit by this too and it was broken by 330a25292d986bd371e3c234f10f5ee34725557a. It wasn't entirely right before either because the CentOS case was indeed missing but it did work via the fallback clause that does it with `/sbin/service #{svc_name} initdb`. Now it's trying to use a versioned postgresql-setup binary when the distro packages do not include this version number. This will only work for PGDG. Please fix this and in such a way that doesn't involve me having to manually set the version attribute as I never had to do it before.

**Comment by slyness** [comment]
Thanks. I'll make sure fix this right away. I am hoping to make a release this week and I'll be sure to address this.

**Comment by slyness** [comment]
There are some issues with the pgdg repository for 9.2 for RHEL systems (ca cert problems with their repositories which need to have ca-certificates updated before the packages for 9.2 can be installed). I have an update coming that fixes that. Slogging through testing.. currently have 9.2 behaving correctly on RHEL. I really hope to have a new release cut today.

**Comment by slyness** [comment]
Please give 3.4.24 a try. Although I didn't run this against your specific ami yet I did however, uncover and correct an issue installing postgresql 9.2 in certain RHEL scenarios. I will keep this open for now and wait to hear from you as well as try and build using the above ami next week after the holiday. But I believe 3.4.24 should be working better now with regards to this issue.

**Comment by chewi** [comment]
Looking good on CentOS here, thanks!

**Comment by slyness** [comment]
Awesome‼️
