### ISSUE TITLE
Permission denied @ rb_sysopen - .../fauxhai/platforms/opensuse/13.2.json

### ISSUE THREAD

**Issue by roblperry** [hw-cookbooks/postgresql#321]
The existing Gemfile depends upon 'chefspec', '~> 4.2.0', which in turn requires depends upon  'fauxhai', '~> 3.0', '>= 3.0.1'.  However, support for opensuse 13.2 was not added to fauxhai until version 4.0 and version 4.0 was not introduced to chef spec until version 4.5.  Thus, I suggest we update the Gemfile to use 'chefspec', '~> 4.5.0'.

**Comment by slyness** [comment]
This has been merged and will be part of the next release.
