### ISSUE TITLE
data_dir atrribute not honoured by postgres

### ISSUE THREAD

**Issue by kemra102** [hw-cookbooks/postgresql#324]
On EL7 systems it seem as though the PGDATA directory is always `/var/lib/pgsql/data` even though the cookbook creates (and places config files inside) `/var/lib/pgsql/8.4/data` it isn't used by the running PostgreSQL process. This means things like `pg_hba.conf` created by the cookbook are never used.

This may be due to the fact that the systemd unit file that ships with the version of postgresql-server in the CentOS repos (9.2) explicitly sets PGDATA to `/var/lib/pgsql/data`.

**Comment by slyness** [comment]
Yes. There are some quirks with the small differences between Centos, RHEL, SUSE and the rpm based distributions that may end up with some cases like this. Thanks for pointing this one out. If you want to submit a PR for updates to your use case that would be awesome. If you are unable to do that please let that be known as well so someone, or myself, can prioritize the issue at some point in the future.

**Comment by kemra102** [comment]
I'll take a stab at it this week.

**Comment by elijahchancey** [comment]
The same thing is happening with Ubuntu 14.04.

**Comment by slyness** [comment]
Thank you. PR is merged for testing and will be included in the next release.
