### ISSUE TITLE
Stop using 'apt' cookbook and calling 'apt-get' directly

### ISSUE THREAD

**Issue by voidmain** [hw-cookbooks/postgresql#357]
Right now the `postgresql` cookbook` is using the `apt` and is also calling `apt-get update` directly (from the `ruby` recipe). This is problematic for a couple of reasons, but most importantly is that the `apt` cookbook and vanilla calls to `apt-get update` timeout on Ubuntu 16.04 in some environments. 

It seems like a better policy to force the users of the `postgresql` cookbook to perform any apt updates themselves rather than doing it in the cookbook. This also allows users to setup their own apt caches and configuration, rather than pulling in all of the configuration from the `apt` cookbook.

**Comment by tenaciousRas** [comment]
This bug report apparently only adds to my configuration workload and doesn't fix or address any issues I'm having with this recipe.  I don't understand what you want to see users of the cookbook to do exactly, can you stub it out?  Should any/every cookbook using apt and apt-get directly stop doing this?

**Comment by voidmain** [comment]
It's been a while since I looked at your code, but I think this was originally an issue with installation inside Kitchen failing consistently. You can probably just delete this issue. I'm not using this cookbook anymore. I wrote my own to capture only what I needed for my deployments.

**Comment by tenaciousRas** [comment]
It's not my code.  Thanks for rescinding the report, I was just dissatisfied with its reproducibility.
