### ISSUE TITLE
installs wrong version on CentOS7

### ISSUE THREAD

**Issue by el-dude** [hw-cookbooks/postgresql#358]
Hello, 

I am trying to install Postgres 9.4 via a [chef provisioner](https://gist.github.com/el-dude/25d810442e558a601fcde9cfa8495238) with Terraform. The run does not fail but it seems to install the wrong version(9.2) of Postgres on the system. This is what my [Environment](https://gist.github.com/el-dude/925e06cc025855b3aaea0c9ee29f4840) looks like. Like I said it never fails, but it does not put the data directory in the path I am specifying in the Environment nor the version, all though it does something weird, it creates this path: `/var/lib/pgsql/9.4/data` in the `postgres.conf` but the version of the binary installed and running is 9.2.
```
[centos@postgres-testing-0 ~]$ postgres --version
postgres (PostgreSQL) 9.2.15
[centos@postgres-testing-0 ~]$ 
```
it seems strange that it doesn't use the path I set in the Environment but it uses the version(9.4) which I set in the Environment in the path `/var/lib/pgsql/9.4/data` for the data directory.

Note: it seems to install the version of the bianary I specify in my environment as well as the wrong postgres(version 9.2) packages from the centos yum repo. 
```
[centos@postgres-testing-0 ~]$ rpm -qa | egrep "postgres|pgdg"
pgdg-centos94-9.4-2.noarch
postgresql-libs-9.2.15-1.el7_2.x86_64
postgresql-devel-9.2.15-1.el7_2.x86_64
postgresql-9.2.15-1.el7_2.x86_64
postgresql-server-9.2.15-1.el7_2.x86_64
[centos@postgres-testing-0 ~]$
```

Operating system version: `CentOS Linux release 7.2.1511 (Core) `

**Comment by luckymike** [comment]
All of the following attributes are involved in what's installed, you probably have to set each of them to the correct value for 9.4 on Cent 7: https://github.com/hw-cookbooks/postgresql/blob/develop/attributes/default.rb#L195-L200

**Comment by el-dude** [comment]
So I modified my [`environment.json`](https://gist.github.com/el-dude/925e06cc025855b3aaea0c9ee29f4840) and I am still not getting desired results. I am seeing that the server packages are getting installed but, it is also installing the 9.2 version which I do not want. It also is actually using the 9.2 version still. 

Also even though I am setting the `"dir": "/postgres/data"` attribute it still uses the default of: `/var/lib/pgsql/9.4/data` even thought the running version is 9.2.

**Comment by el-dude** [comment]
OK, I am able to get the correct version installed and started [`environment.json`](https://gist.github.com/el-dude/1aa9244d3a9fa04b137ecae9bc68c5d1). ;) 

I now need to figure out why it still is installing the 9.2 version...

Actually I think I figured it out. I think what is happening is that the the things I want to do would need to be done as an override in the environment as it seems to be joining them instead of overriding them. so I am just going to use a quick thin wrapper that I can use to do the overrides. I can then set the version in the environment and use attributes in the wrapper to do the overriding. 

Thanks for helping out. 

Cory
