### ISSUE TITLE
Cookbook continuously tries to set password

### ISSUE THREAD

**Issue by hufman** [hw-cookbooks/postgresql#98]
Every time the server.rb recipe is run, it runs a shell command to reset the postgres password to the node[:postgresql][:password][:postgres] attribute. The comment above it says that the cookbook does not have access to the plaintext password.
However, in the case where the recipe has set the password automatically around line 47, the plaintext password is saved in the attribute. In fact, if the attribute does not start with md5, it can be assured to be a plain-text password.

Please bring back the old behavior, where (if the stored password is plaintext) the recipe will attempt to authenticate with the stored password before trying to reset it.

The only real reason is that error messages show up in the postgresql log if the password is attempted to be altered while the server is running as a hot_standby.

**Comment by slyness** [comment]
Resolved with #158
